[phases.setup]
nixPkgs = [
  "python310", 
  "python310Packages.setuptools", 
  "python310Packages.pip", 
  "python310Packages.wheel"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.start]
gunicorn Code.HumanAction.wsgi:application --bind 0.0.0.0:${PORT:-8000}

