services:
  - type: web
    name: human-action-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn HumanAction.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: HumanAction.settings
